import 'reflect-metadata';
import { Container } from 'inversify';
import { DiscordLibrary } from '../infrastructure/library/DiscordLibrary';
import { SYMBOLS } from './symbols';
import { DiscordBot } from '../interfaces/DiscordBot';
import { InsiderServiceImpl } from '../application/impl/InsiderServiceImpl';
import { InsiderService } from '../application/InsiderService';
import { DiscordService } from '../domain/service/discord/DiscordService';
import { InsiderGameService } from '../domain/service/insider/InsiderGameService';
import { ThemeLibrary } from '../infrastructure/library/ThemeLibrary';
import { DiscordMessageService } from '../domain/service/discord/DiscordMessageService';
import { TimerService } from '../domain/service/common/TimerService';

export const container = new Container({ defaultScope: 'Singleton' });
container.bind<DiscordLibrary>(SYMBOLS.DiscordLibrary).to(DiscordLibrary);
container.bind<DiscordBot>(SYMBOLS.DiscordBot).to(DiscordBot);
container.bind<DiscordService>(SYMBOLS.DiscordService).to(DiscordService);
container.bind<DiscordMessageService>(SYMBOLS.DiscordMessageService).to(DiscordMessageService);
container.bind<InsiderService>(SYMBOLS.InsiderService).to(InsiderServiceImpl);
container.bind<InsiderGameService>(SYMBOLS.InsiderGameService).to(InsiderGameService);
container.bind<ThemeLibrary>(SYMBOLS.ThemeLibrary).to(ThemeLibrary);
container.bind<TimerService>(SYMBOLS.TimerService).to(TimerService);
